name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build_desktop:
    name: Build Desktop App
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Desktop App
        uses: openMF/mifos-x-actionhub-build-desktop-app-kmp@v1.0.1
        with:
          desktop_package_name: 'Moribito'
          java-version: '21'