name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  package:
    name: Package Distribution
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JetBrains Runtime
        uses: JetBrains/setup-jbr@v1
        with:
          version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Package Distribution
        run: ./gradlew :gui:packageDistributionForCurrentOS

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: moribito-${{ matrix.os }}
          path: gui/build/compose/binaries/main/**
